name: h2o-wildfire
channels:
  - conda-forge
  - defaults
dependencies:
  - catboost.cbm=1.0.3
  - fiona=1.8.20
  - flask=2.0.2
  - geopandas=0.10.2
  - lightgbm=3.3.1
  - nbformat=5.1.3
  - plotly=5.4.0
  - python=3.8.12
  - requests=2.26.0