name: h2o-wildfire
channels:
  - conda-forge
  - defaults
dependencies:
  - catboost=1.0.3
  - dash=2.2.0
  - dash-core-components=2.0.0
  - dash-html-components=2.0.0
  - dash-table=5.0.0
  - fiona=1.8.20
  - flask=2.0.2
  - geopandas=0.10.2
  - graphviz=2.50.0
  - lightgbm=3.3.1
  - nbformat=5.1.3
  - pandas=1.4.1
  - plotly=5.4.0
  - pyproj=3.3.0
  - python=3.8.12
  - requests=2.26.0
  - shap=0.40.0
  - shapely=1.8.0